name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for taking the time to create an issue. We will defintely look into this. Also you are free to contribute"
        pr-message: "Thanks a lot for pull request. I will review it ASAP and get back to you."
